import { createFileRoute, useParams, useNavigate, Link } from "@tanstack/react-router";
import { useState } from "react";
import { AppLayout } from "@/components/app-layout";
import { StatusBadge } from "@/components/status-badge";
import { mockApplications } from "@/lib/mock-data";
import { toast } from "sonner";
import { ArrowLeft, Send, Sparkles, Save, Trash2, MapPin, Briefcase } from "lucide-react";
import {
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogCancel,
  AlertDialogAction,
} from "@/components/ui/alert-dialog";

export const Route = createFileRoute("/applications/$id")({
  head: () => ({ meta: [{ title: "Application — AutoApply" }] }),
  component: ApplicationDetail,
});

function ApplicationDetail() {
  const { id } = useParams({ from: "/applications/$id" });
  const navigate = useNavigate();
  // API: GET /api/v1/applications/:id
  const app = mockApplications.find((a) => a.id === id) ?? mockApplications[0];

  const [hrEmail, setHrEmail] = useState(app.hrEmail);
  const [subject, setSubject] = useState(app.emailSubject);
  const [body, setBody] = useState(app.emailBody);
  const [instructions, setInstructions] = useState("");

  const save = () => {
    // API: PUT /api/v1/applications/:id
    toast.success("Changes saved");
  };

  const send = () => {
    // API: POST /api/v1/applications/:id/send
    toast.success(`Email sent to HR at ${app.companyName}`);
    navigate({ to: "/applications" });
  };

  const regenerate = () => {
    // API: POST /api/v1/applications/:id/regenerate
    toast.info("Draft regenerated by AI");
  };

  const discard = () => {
    // API: POST /api/v1/applications/:id/discard
    toast.success("Application discarded");
    navigate({ to: "/applications" });
  };

  return (
    <AppLayout>
      <div className="space-y-6">
        <Link
          to="/applications"
          className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" /> All applications
        </Link>

        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <div className="eyebrow">{app.source}</div>
            <h1 className="mt-2 text-3xl font-medium tracking-tight sm:text-4xl">
              {app.jobTitle}
            </h1>
            <div className="mt-1 text-sm text-muted-foreground">@ {app.companyName}</div>
          </div>
          <StatusBadge status={app.status} className="text-sm" />
        </div>

        <div className="grid gap-6 lg:grid-cols-5">
          {/* LEFT: job details */}
          <aside className="lg:col-span-2">
            <div className="rounded-[32px] bg-card p-6 shadow-[var(--shadow-pill)]">
              <div className="eyebrow">Job details</div>
              <div className="mt-4 space-y-3 text-sm">
                <Row label="Company" value={app.companyName} />
                <Row label="Title" value={app.jobTitle} />
                <Row
                  label="HR email"
                  value={
                    <input
                      value={hrEmail}
                      onChange={(e) => setHrEmail(e.target.value)}
                      className="w-full rounded-full border border-foreground/15 bg-card px-3 py-1 text-sm outline-none focus:border-foreground/40"
                    />
                  }
                />
                <Row
                  label="Location"
                  value={
                    <span className="inline-flex items-center gap-1">
                      <MapPin className="h-3 w-3" /> {app.jobLocation}
                    </span>
                  }
                />
                <Row
                  label="Type"
                  value={
                    <span className="inline-flex items-center gap-1">
                      <Briefcase className="h-3 w-3" /> {app.employmentType}
                    </span>
                  }
                />
                <Row
                  label="Created"
                  value={new Date(app.createdAt).toLocaleString()}
                />
              </div>

              <div className="mt-6">
                <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                  Skills required
                </div>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {app.skillsRequired.map((s) => {
                    const matched = app.skillsMatched.includes(s);
                    return (
                      <span
                        key={s}
                        className={`rounded-full px-3 py-1 text-xs ${
                          matched
                            ? "bg-[oklch(0.94_0.06_150)] text-[oklch(0.4_0.13_150)]"
                            : "bg-secondary text-foreground/70"
                        }`}
                      >
                        {s}
                        {matched && " ✓"}
                      </span>
                    );
                  })}
                </div>
                <div className="mt-3 text-xs text-muted-foreground">
                  {app.skillsMatched.length} of {app.skillsRequired.length} skills matched
                </div>
              </div>
            </div>
          </aside>

          {/* RIGHT: email draft */}
          <div className="lg:col-span-3">
            <div className="rounded-[32px] bg-card p-6 shadow-[var(--shadow-pill)]">
              <div className="flex items-center justify-between">
                <div className="eyebrow">Email draft</div>
                <span className="text-xs text-muted-foreground">to {hrEmail}</span>
              </div>

              <label className="mt-4 block">
                <span className="text-xs font-medium text-muted-foreground">Subject</span>
                <input
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  className="mt-1 w-full rounded-full border border-foreground/15 bg-card px-4 py-2.5 text-sm outline-none focus:border-foreground/40"
                />
              </label>

              <label className="mt-4 block">
                <span className="text-xs font-medium text-muted-foreground">Body</span>
                <textarea
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  rows={16}
                  className="mt-1 w-full resize-y rounded-2xl border border-foreground/15 bg-lifted p-4 font-mono text-[13px] leading-relaxed outline-none focus:border-foreground/40"
                />
              </label>

              <details className="mt-4 rounded-2xl border border-foreground/10 bg-lifted p-4">
                <summary className="cursor-pointer text-sm font-medium">
                  Regeneration instructions (optional)
                </summary>
                <textarea
                  value={instructions}
                  onChange={(e) => setInstructions(e.target.value)}
                  placeholder="e.g. Make it shorter, mention my AWS certifications, more conversational tone…"
                  rows={3}
                  className="mt-3 w-full resize-y rounded-2xl border border-foreground/15 bg-card p-3 text-sm outline-none focus:border-foreground/40"
                />
              </details>

              <div className="mt-6 flex flex-wrap items-center gap-2">
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <button className="inline-flex items-center gap-2 rounded-full bg-foreground px-6 py-2.5 text-sm font-medium text-background">
                      <Send className="h-4 w-4" />
                      Send email
                    </button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>Send this email?</AlertDialogTitle>
                      <AlertDialogDescription>
                        We'll dispatch from your Gmail to{" "}
                        <span className="font-medium">{hrEmail}</span>. This can't be undone.
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                      <AlertDialogAction onClick={send}>Send</AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>

                <button
                  onClick={save}
                  className="inline-flex items-center gap-2 rounded-full border border-foreground/20 bg-card px-5 py-2.5 text-sm font-medium hover:bg-secondary"
                >
                  <Save className="h-4 w-4" /> Save changes
                </button>

                <button
                  onClick={regenerate}
                  className="inline-flex items-center gap-2 rounded-full border border-foreground/20 bg-card px-5 py-2.5 text-sm font-medium hover:bg-secondary"
                >
                  <Sparkles className="h-4 w-4" /> Regenerate
                </button>

                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <button className="ml-auto inline-flex items-center gap-2 rounded-full border border-destructive/30 bg-card px-5 py-2.5 text-sm font-medium text-destructive hover:bg-destructive/5">
                      <Trash2 className="h-4 w-4" /> Discard
                    </button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>Discard this application?</AlertDialogTitle>
                      <AlertDialogDescription>
                        The draft will be archived. You can restore it within 30 days.
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Keep</AlertDialogCancel>
                      <AlertDialogAction onClick={discard}>Discard</AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </div>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="grid grid-cols-3 items-center gap-3">
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="col-span-2 text-sm">{value}</div>
    </div>
  );
}
